version: '3.8'

services:
  hadoop-single:
    build: .
    container_name: hadoop-single
    hostname: hadoop-single
    ports:
      - "9870:9870"  # HDFS NameNode Web UI
      - "8088:8088"  # YARN ResourceManager Web UI
      - "9864:9864"  # DataNode Web UI
      - "8042:8042"  # NodeManager Web UI
      - "9000:9000"  # HDFS NameNode
    volumes:
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - hadoop-data:/tmp/hadoop-root
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk
    command: >
      bash -c "
        service ssh start &&
        hdfs namenode -format -force &&
        start-dfs.sh &&
        start-yarn.sh &&
        tail -f /dev/null
      "

volumes:
  hadoop-data: